name: Continuous Integration and Delivery with Github Actions

on:
  push:
    branches:
      - "main"
      - "master"


jobs:
  build:
    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v4

    - name: Verificar estrutura de diretórios
      run: |
        echo "Diretório atual:"
        pwd
        echo "Conteúdo da raiz:"
        ls -R



    - name: Login to Docker hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Setup Java 21
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build Application .jar
      working-directory: ./api_rest
      run: mvn clean package

    - name: Docker Compose Build
      #working-directory: .
      run: docker compose build


    - name: Push to Docker Hub Container Registry
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/api-rest:latest ${{ secrets.DOCKER_USERNAME }}/api-rest:${{ github.run_id }}
        
        docker push ${{ secrets.DOCKER_USERNAME }}/api-rest:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/api-rest:${{ github.run_id }}