name: Continuous Integration and Delivery with Github Actions

on:
  push:
    branches:
      - "main"


jobs:
  build:
    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v4

    - name: 🔍 Debug - Mostrar estrutura de arquivos
      run: |
        echo "Diretório atual:"
        pwd
        echo "Conteúdo da raiz do repositório:"
        ls -la
        echo "Conteúdo da pasta JavaLearning2:"
        ls -la JavaLearning2 || echo "Pasta JavaLearning2 não encontrada"
        echo "Conteúdo da pasta JavaLearning2/api-rest:"
        ls -la JavaLearning2/api-rest || echo "Pasta JavaLearning2/api-rest não encontrada"


    - name: Login to Docker hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Setup Java 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build Application .jar
      working-directory: .
      run: mvn clean package

    - name: Docker Compose Build
      working-directory: .
      run: docker compose build

    - name: Push to Docker Hub Container Registry
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/api-rest:latest ${{ secrets.DOCKER_USERNAME }}/api-rest:${{ github.run_id }}
        
        docker push ${{ secrets.DOCKER_USERNAME }}/api-rest:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/api-rest:${{ github.run_id }}